services:
  front:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - HTTP_PROXY
        - HTTPS_PROXY
        - NO_PROXY

    ports:
      - "3000:3000"
    volumes:
      - "./frontend:/frontend"
      - "/frontend/node_modules"

